### ISSUE TITLE
kubernetes_asyncio regression: AttributeError("'ClientResponse' object has no attribute 'getheader'") in ResourceReflector

### ISSUE THREAD

**Issue by takeshi-yashiro** [jupyterhub/kubespawner#580]
### Bug description

`AttributeError("'ClientResponse' object has no attribute 'getheader'")` is caused and spawning status of user server is not updated, while the corresponding pod is spawned correctly and is ready on k8s.

The following error log is found in the jupyterhub container log:
```
Traceback (most recent call last):
  File ""/usr/local/lib/python3.8/dist-packages/kubespawner/reflector.py"", line 392, in start
    await self._list_and_update()
  File ""/usr/local/lib/python3.8/dist-packages/kubespawner/reflector.py"", line 236, in _list_and_update
    initial_resources_raw = await list_method(**kwargs)
  File ""/usr/local/lib/python3.8/dist-packages/kubernetes_asyncio/client/api_client.py"", line 191, in __call_api
    content_type = response_data.getheader('content-type')
AttributeError: 'ClientResponse' object has no attribute 'getheader'
future: <Task finished name='Task-5' coro=<ResourceReflector.start() done, defined at /usr/local/lib/python3.8/dist-packages/kubespawner/reflector.py:379> exception=AttributeError("'ClientResponse' object has no attribute 'getheader'")>
ERROR:asyncio:Task exception was never retrieved
Traceback (most recent call last):
  File ""/usr/local/lib/python3.8/dist-packages/kubespawner/reflector.py"", line 392, in start
    await self._list_and_update()
  File ""/usr/local/lib/python3.8/dist-packages/kubespawner/reflector.py"", line 236, in _list_and_update
    initial_resources_raw = await list_method(**kwargs)
  File ""/usr/local/lib/python3.8/dist-packages/kubernetes_asyncio/client/api_client.py"", line 191, in __call_api
    content_type = response_data.getheader('content-type')
AttributeError: 'ClientResponse' object has no attribute 'getheader'"
future: <Task finished name='Task-4' coro=<ResourceReflector.start() done, defined at /usr/local/lib/python3.8/dist-packages/kubespawner/reflector.py:379> exception=AttributeError("'ClientResponse' object has no attribute 'getheader'")>
ERROR:asyncio:Task exception was never retrieved
```

It seems that this error is caused by specification of `_preload_content=False` in kubespawner/reflector.py, as kubenetes_asyncio returns raw `aiohttp.ClientResponse` object (which does not have `getheader` method) instead of `RESTResponse` object (eqipped with `getheader`  method) that wraps ClientResponse, when `_preload_content` is set False. Evidence of this behavior in `kubernetes_asyncio` can be found at: https://github.com/tomplus/kubernetes_asyncio/blob/da1e3172acd098e5feb47193bd9d73428078b61a/kubernetes_asyncio/client/rest.py#L178-L189

### Your personal set up

 - OS: ubuntu 20.04
 - Version(s): jupyterhub 2.2.0, python 3.8.10
- kubespawner : main:HEAD @ [0b6ad95](https://github.com/jupyterhub/kubespawner/commit/0b6ad95698f395975ad3642820e6919e98354803)

**Comment by consideRatio** [comment]
## References
- This is code referenced by @takeshi-yashiro
   ```python
        r = await self.pool_manager.request(**args)
        if _preload_content:

            data = await r.read()
            r = RESTResponse(r, data)

            # log response body
            logger.debug("response body: %s", r.data)

            if not 200 <= r.status <= 299:
                raise ApiException(http_resp=r)

        return r
  ```
- [`self.pool_manager` is a `aiohttp.ClientSession` object](https://github.com/tomplus/kubernetes_asyncio/blob/da1e3172acd098e5feb47193bd9d73428078b61a/kubernetes_asyncio/client/rest.py#L79-L82)
- [`aiohttp.ClientSession.request` method returns an `aiohttp.ClientResponse` object](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.trace_config)
- [aiohttp.ClientResponse object reference](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientResponse)

## Investigation

Hmmm... It seems that the erroring code is related to a bug in `kubernetes_asyncio` that has been fixed in https://github.com/tomplus/kubernetes_asyncio/pull/123. I assume the issue you experience is related to the version of `kubernetes_asyncio`. This project requires a very modern version of it. I assume you have an outdated version, older than what is declared to be required by kubespawner.

https://github.com/jupyterhub/kubespawner/blob/0b6ad95698f395975ad3642820e6919e98354803/setup.py#L17-L26

**Comment by consideRatio** [comment]
@takeshi-yashiro can you verify that you had an outdated version of `kubernetes_asyncio`?

**Comment by takeshi-yashiro** [comment]
Yes, I confirmed that I'm using the latest version of `kubernetes_asyncio` in PyPI as follows, and the error persists.

```
root@jupyterhub-75b6d9dcf4-2wmzs:/opt# pip3 freeze  | grep kube
jupyterhub-kubespawner @ git+https://github.com/jupyterhub/kubespawner.git@0b6ad95698f395975ad3642820e6919e98354803
kubernetes-asyncio==21.7.0
```

And this is the Dockerfile I use. By simply changing `git+https://github.com/jupyterhub/kubespawner.git` to `jupyterhub-kubespawner`, I no longer see the same error. 

```
FROM jupyterhub/jupyterhub:2.2.0

WORKDIR /opt
RUN apt-get -qq update && apt-get -qq upgrade && apt-get install -y nfs-common git \
    && pip install requests-futures oauthenticator \
                   git+https://github.com/jupyterhub/kubespawner.git \
                   jupyterhub-idle-culler mysql-connector-python \
    && openssl rand -hex 1024 > configproxy.token \
    && openssl rand -hex 32 > cookie.secret \
    && mkdir -p /mnt/jupyterhub \
    && apt-get remove -y git && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
...(omitted)...
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod a+rx /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD [""]
```

**Comment by consideRatio** [comment]
Hmmm... But this section, has been removed from the code base of `kubernetes_asyncio` I thought...

```
  File ""/usr/local/lib/python3.8/dist-packages/kubernetes_asyncio/client/api_client.py"", line 191, in __call_api
    content_type = response_data.getheader('content-type')
```

Well, looking at the code instead of using github search, I find it: https://github.com/tomplus/kubernetes_asyncio/blob/da1e3172acd098e5feb47193bd9d73428078b61a/kubernetes_asyncio/client/api_client.py#L191

Making some git blame inspection, I conclude it is an upstream regression recently introduced. I verified that [by re-running our test suite](https://github.com/jupyterhub/kubespawner/runs/5496015146?check_suite_focus=true) against the recently released `kubernetes_asyncio` package. I opened https://github.com/tomplus/kubernetes_asyncio/issues/183 about this.

**Comment by takeshi-yashiro** [comment]
Thank you! I confirmed that the problem is solved by updating `kubernetes_asyncio` to 21.7.1, just released by tomplus/kubernetes_asyncio#183.

**Comment by consideRatio** [comment]
@takeshi-yashiro thank you! :heart: :tada:!
